# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yx1aoq1's Blog
subtitle:
description:
author: Yx1aoq1
language: zh-cn
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: bmw-theme

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: 
  type: git #部署类型，使用github
  repository: https://Yx1aoq1:Tmd.233!@github.com/Yx1aoq1/Yx1aoq1.github.io.git #部署的仓库SSH
  branch: master #部署的分支
  message: update #默认类型

backup: 
  type: git
  repository: 
    github: https://github.com/Yx1aoq1/Yx1aoq1.github.io.git,hexo

archive_generator:
    per_page: 0
    yearly: false
    monthly: false
    daily: false

admin:
  username: Yx1aoq1
  password_hash: $2a$10$7Zy74YMIwIZuWpDCLjyOk.o1MbhN.dENI/.66Nuh9WKz.kKoewIt6
  secret: hey hexo
  deployCommand: './admin_script/hexo-deploy.sh'
    
# #archer主题配置
# jsonContent:
#   meta: false
#   pages: false
#   posts:
#     title: true
#     date: true
#     path: true
#     text: false
#     raw: false
#     content: false
#     slug: false
#     updated: false
#     comments: false
#     link: false
#     permalink: false
#     excerpt: false
#     categories: false
#     tags: true