# ========== Profile ========== #
# avatar
avatar: /avatar/kagura.jpg
# author name
author: Yx1aoq1
# signature
signature: Salted fish every day
# SNS
social:
  email: yanx1aoq1@gmail.com
  github: //github.com/Yx1aoq1
  weibo: http://weibo.com/4shero
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
  # others:
  rss: /atom.xml
# friends
friends:
  #friendA: //www.baidu.com
  #friendB: //www.google.com
  # friendC :
about:
  enable: true
  image: '/intro/about-page.jpg'

# ========== Site ========== #
# title of the site
SEO_title: Yx1aoq1's Blog
# main title
main_title: Yx1aoq1's Blog.
# subtitle
subtitle: it's better to burn out than to fade away
# site haeder image
site_header_image: '/intro/intro-desktop-3.jpeg'
# post haeder image
post_header_image: '/intro/post-bg-3.jpeg'
# 404 image
#_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # livere  site: https://livere.com/
  livere_uid:
  # disqus  site: https://disqus.com/
  disqus_shortname:
  # changyan  site: http://changyan.kuaizhan.com/
  changyan_appid:
  changyan_conf:
  # gitment  site: https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: false
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assests/favicon.ico
# truncate length (the default is 300)
truncate_length:
# enable toc
toc: true
